---
esphome:
  name: cherrybutton

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  password: !secret psk_ota

#output:
#  #BuiltInLED Removed in favour of using onboard LED
#  - platform: gpio
#    pin:
#      number: D4
#      mode: output
#    id: LED

matrix_keypad:
  id: CherryButtons
  rows:
    - pin: D4
    - pin: D6
    - pin: D7
  columns:
    - pin: D3
    - pin: D2
    - pin: D1
  keys: "789456123"
  has_diodes: true

binary_sensor:
  # MasterSwitch
  - platform: matrix_keypad
    keypad_id: CherryButtons
    key: 9
    name: Master cherry switch off 
    id: cherry_lightswitch_9
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
  - platform: matrix_keypad
    keypad_id: CherryButtons
    key: 8
    name: AC Cherry Switch
    id: cherry_lightswitch_8
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
  - platform: matrix_keypad
    keypad_id: CherryButtons
    key: 7
    name: Master cherry switch
    id: cherry_lightswitch7
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
  - platform: matrix_keypad
    keypad_id: CherryButtons
    key: 6
    name: Button 6
    id: cherry_lightswitch6
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
    # MasterSwitch
  - platform: matrix_keypad
    keypad_id: CherryButtons
    key: 5
    name: Bedroom cherry switch
    id: cherry_lightswitch_5
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
  - platform: matrix_keypad
    keypad_id: CherryButtons
    key: 4
    name: Button 4
    id: cherry_lightswitch_4
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
  # MasterSwitch
  - platform: matrix_keypad
    keypad_id: CherryButtons
    key: 3
    name: Button 3
    id: cherry_lightswitch_3
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
  - platform: matrix_keypad
    keypad_id: CherryButtons
    key: 2
    name: Button 2
    id: cherry_lightswitch_2
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
  - platform: matrix_keypad
    keypad_id: CherryButtons
    key: 1
    name: Button1
    id: cherry_lightswitch_1
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
  
wifi:
  ssid: !secret SSID
  password: !secret psk_wifi

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cherrybutton Fallback Hotspot"
    password: !secret psk_fallbackAP

captive_portal:
    