---
esphome:
  name: cherrybutton

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  password: !secret psk_ota

output:
  #BuiltInLED Removed in favour of using onboard LED
  #- platform: gpio
  #  pin:
  #    number: D4
  #    mode: output
  #  id: LED

binary_sensor:
  # MasterSwitch
  - platform: gpio
    pin:
      number: D1
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false
      inverted: true
    name: Master cherry switch
    id: cherry_lightswitch1
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
    on_state:
      then:
        - if:
            condition:
              or:
                - binary_sensor.is_on: cherry_lightswitch1
            then:
              - output.turn_off: LED
            else:
              - output.turn_on: LED
    # MasterSwitch
  - platform: gpio
    pin:
      number: D2
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false
      inverted: true
    name: Bedroom cherry switch
    id: cherry_lightswitch2
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
    on_state:
      then:
        - if:
            condition:
              or:
                - binary_sensor.is_on: cherry_lightswitch2
            then:
              - output.turn_off: LED
            else:
              - output.turn_on: LED
  # MasterSwitch
  - platform: gpio
    pin:
      number: D3
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false
      inverted: true
    name: AC cherry switch
    id: cherry_lightswitch3
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
    on_state:
      then:
        - if:
            condition:
              or:
                - binary_sensor.is_on: cherry_lightswitch3
            then:
              - output.turn_off: LED
            else:
              - output.turn_on: LED
  # MasterSwitch
  - platform: gpio
    pin:
      number: D4
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false
      inverted: true
    name: Master cherry switch off 
    id: cherry_lightswitch4
    device_class: ''
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
    on_state:
      then:
        - if:
            condition:
              or:
                - binary_sensor.is_on: cherry_lightswitch4
            then:
              - output.turn_off: LED
            else:
              - output.turn_on: LED

wifi:
  ssid: !secret SSID
  password: !secret psk_wifi

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cherrybutton Fallback Hotspot"
    password: !secret psk_fallbackAP

captive_portal:
    